# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HealthApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthApp
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FirebaseUI', '~> 1.0'
  pod 'GoogleSignIn'
  pod 'Kanna', '~> 2.1.0'

  target 'HealthAppTests' do
   pod 'Firebase'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   pod 'Firebase/Auth'
   pod 'FirebaseUI', '~> 1.0'
   pod 'GoogleSignIn'
   pod 'Kanna', '~> 2.1.0'

   inherit! :search_paths
   # Pods for testing
  end

  target 'HealthAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
